"""del: unique_agenda_entry

Revision ID: 8da1ba3e178c
Revises: d07448647787
Create Date: 2025-01-06 10:19:29.756426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da1ba3e178c'
down_revision = 'd07448647787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.drop_constraint('unique_agenda_entry', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agenda', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_agenda_entry', ['responsable_id', 'actividad_id', 'dia_id'])

    # ### end Alembic commands ###
