"""first migration

Revision ID: d07448647787
Revises: 
Create Date: 2025-01-06 09:30:59.530824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07448647787'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Enum('lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo', name='dias_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('responsable', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('responsable')
    )
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('actividad_id', sa.Integer(), nullable=True),
    sa.Column('dia_id', sa.Integer(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['dia_id'], ['dias.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['responsables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('responsable_id', 'actividad_id', 'dia_id', name='unique_agenda_entry')
    )
    op.create_table('detalle_actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=True),
    sa.Column('tarea_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_actividades')
    op.drop_table('agenda')
    op.drop_table('tareas')
    op.drop_table('responsables')
    op.drop_table('dias')
    op.drop_table('actividades')
    # ### end Alembic commands ###
